apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 5g-nr-data-pvc
  namespace: 5g-nr-agents
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
